### ISSUE TITLE
Automated Tests: Continuous Integration and Testing

### ISSUE THREAD

**Issue by hayesall** [elwinter/nnde#12]
**Recommendation**: Run tests automatically on a push. [GitHub Actions](https://docs.github.com/en/actions/guides/building-and-testing-python) or a Continuous Integration (CI) service should help here (Circle-CI, Travis-CI, AppVeyor, etc.)

**Comment by elwinter** [comment]
I configured a GitHub action to automatically run the test suite using pytest and tox. The runs are triggered on a repository push. I'll remove one of the tests runs once I decide which is more useful, report-wise.
