### ISSUE TITLE
[feature-request] Evaluating with initial conditions other than `Y(0)`

### ISSUE THREAD

**Issue by hayesall** [elwinter/nnde#21]
Imagine that I want to evaluate the `y′ - 2y = x / (1 + y²)` with the initial condition `y(1) = 7.0`.

This does not currently appear to be possible, and all initial conditions are written in terms of `Y(0)`.

---

Possible API: Perhaps passing a *float* could still represent the initial condition at 0.0, but passing `ode.ic` as a tuple represents the initial value of `(x, Y(x))`. For example: `(1.0, 7.0)` would represent `Y(1.0) = 7.0`.

```python
>>> from nnde.differentialequation.ode.ode1ivp import ODE1IVP
>>> ode = ODE1IVP()
>>> ode.id = (1.0, 7.0)
```

**Comment by ewinterapl** [comment]
I understand the suggestion. But the current version of the software was designed to work on orthonormalized problem domains. So for an ordinary differential equation, the problem must be formulated (typically via variable scaling) to be solved on the domain [0, 1]. For a 2-variable PDE, the domain must be [[0, 1], [0, 1]]. This does not restrict the problems that can be solved, but it does require the equation to be suitably scaled.
