### ISSUE TITLE
Documentation: Installation

### ISSUE THREAD

**Issue by hayesall** [elwinter/nnde#6]
Installation instructions should be included in the main README and associated documentation.

**Recommendation**:

- Command for installing from source on GitHub (e.g. clone and `pip install -e .`)
- Command for installing from PyPi (https://pypi.org/project/nnde/)

**Comment by elwinter** [comment]
Sorry, guess i assumed knowledge of pip. Will address this and prerequisites tonight or tomorrow and resubmit.

Thanks for the feedback
Eric

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Alexander L. Hayes ***@***.***>
Sent: Tuesday, July 13, 2021 4:58:49 PM
To: elwinter/nnde ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elwinter/nnde] Documentation: Installation (#6)


Installation instructions should be included in the main README and associated documentation.

Recommendation:

  *   Command for installing from source on GitHub (e.g. clone and pip install -e .)
  *   Command for installing from PyPi (https://pypi.org/project/nnde/)

**Comment by rweigel** [comment]
It is standard to include dependencies in `setup.py`. Without it, the user would need to search for all of the import statements to determine dependencies.

**Comment by rweigel** [comment]
Test by creating a virtual environment and executing `pip install nnde` followed by execution of a test or demo. I thought that I did this when testing but clearly I missed it.

**Comment by rweigel** [comment]
I suggest adding the following section to `README.md`

# Installation

To install the library, use

```bash
git clone https://github.com/elwinter/nnde.git
cd nnde; pip install -e .
```

or

```bash
pip install nnde
```

The demos are stored in a separate repository. To use them, execute

```
git clone https://github.com/elwinter/nnde_demos
cd nnde_demos
python lagaris01_demo.py
python nnpde2diff_demo.py
```

**Comment by hayesall** [comment]
Good recommendation @rweigel. #4 also includes the point for adding all requirements under `install_requires` in `setup.py`.

**Comment by elwinter** [comment]
Instructions for installing from PyPI using pip, and by cloning the GitHub repository, have been added to the top-level README.md.
