### ISSUE TITLE
Installation Instructions: Demos

### ISSUE THREAD

**Issue by hayesall** [elwinter/nnde#8]
The [`nnde_demos`](https://github.com/elwinter/nnde_demos) repository has additional requirements beyond those required by the main repository.

**Recommendation**: A `requirements.txt` is a common convention where these are listed out. (`numpy`, `matplotlib`, `scipy`)

**Comment by elwinter** [comment]
A requirements.txt file listing numpy, scipy, and matplotlib has been added, and tested to ensure that it can be used to install the required modules with:

pip install -r requirements.txt
