### ISSUE TITLE
Example Usage: Narrative examples to guide new users

### ISSUE THREAD

**Issue by hayesall** [elwinter/nnde#9]
The [`nnde_demos`](https://github.com/elwinter/nnde_demos) repository has good notes, but their presentation makes them difficult to follow.

**Recommendation**: Include Sphinx documentation or Jupyter notebooks to show steps of the computation alongside the narration for what occurs.

---

[`sphinx`](https://www.sphinx-doc.org/en/master/) documentation with the [`sphinx-gallery`](https://sphinx-gallery.github.io/stable/index.html) plugin is one option, or Jupyter notebooks can usually be rendered on GitHub.

For a real-world example of the `sphinx-gallery` approach, [here is a web page](https://imbalanced-learn.org/stable/auto_examples/api/plot_sampling_strategy_usage.html) that is generated from a [markdown document](https://github.com/scikit-learn-contrib/imbalanced-learn/blob/master/examples/api/plot_sampling_strategy_usage.py)

**Comment by elwinter** [comment]
I added a Jupyter notebook (tutorial.ipynb) to the nnde_demos repository (https://github.com/elwinter/nnde_demos) that walks the user through the process of solving a 1st-order ODE IVP using the nnde ppackage and examining the resulting network and the solutions it generates.
